version: '3.1'

services:
  db-mysql:
    container_name: db-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
      MYSQL_DATABASE: db_example
    volumes:
      - test-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  db-postgres:
    container_name: db-postgres
    image: postgres:9
    restart: always
    environment:
      POSTGRES_USER: my-user
      POSTGRES_PASSWORD: my-secret
      POSTGRES_DB: db_example
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  test-mysql-data:
  test-postgres-data: